import HeaderBar from '@/src/components/layout/HeaderBar';
import { TokenProvider } from '@/src/context/TokenContext';
import { Metadata } from 'next';
import { NextIntlClientProvider, useMessages } from 'next-intl';
import { ThemeProvider } from 'next-themes';
import { Montserrat } from 'next/font/google';
import { ReactNode } from 'react';
import SessionWrapper from '@/src/components/layout/SessionWrapper';

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Smartaste",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
  params: { locale: string };
};

export default function LocaleLayout({ children, params: { locale } }: Props) {
  const messages = useMessages();

  return (
    <html lang={locale}>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta httpEquiv="X-UA-Compatible" content="ie=edge" />
      </head>
      <body className={inter.className} suppressHydrationWarning={true}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <NextIntlClientProvider messages={messages}>
            <div className="app-container">
              <SessionWrapper> 
                <TokenProvider>
                  <HeaderBar />
                  <main>{children}</main>
                </TokenProvider>
              </SessionWrapper>
            </div>
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
