// [locale]/layout.tsx
import HeaderBar from '@/src/components/layout/HeaderBar';
import SessionWrapper from '@/src/components/layout/SessionWrapper';
import { TokenProvider } from '@/src/context/TokenContext';
import { Metadata } from 'next';
import { NextIntlClientProvider, useMessages } from 'next-intl';
import { ThemeProvider } from 'next-themes';
import { Montserrat } from 'next/font/google';
import { ReactNode } from 'react';

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
  params: { locale: string };
};

export default function LocaleLayout({ children, params: { locale } }: Props) {
  const messages = useMessages();

  return (
    <SessionWrapper>
       <TokenProvider>
      <html lang={locale}>
        <head>
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <meta httpEquiv="X-UA-Compatible" content="ie=edge" />
        </head>
        <body className={inter.className} suppressHydrationWarning={true}>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <NextIntlClientProvider messages={messages}>
              <div className="app-container">
                <HeaderBar />
                <main>{children}</main>
              </div>
            </NextIntlClientProvider>
          </ThemeProvider>
        </body>
      </html>
      </TokenProvider>
    </SessionWrapper>
  );
}
